# AUTOMATICALLY GENERATED
# DO NOT EDIT THIS FILE DIRECTLY, USE /templates/Gemfile.erb

source "https://rubygems.org"

gem "fluentd", "1.16.1"
gem "oj", "3.11.0"
gem "ffi"
gem "fluent-plugin-multi-format-parser", "~> 1.0.0"
gem "fluent-plugin-concat", "~> 2.5.0"
gem "fluent-plugin-grok-parser", "~> 2.6.2"
gem 'fluent-plugin-json-in-json-2', ">= 1.0.2"
gem "fluent-plugin-rewrite-tag-filter", "~> 2.4.0"
gem "fluent-plugin-parser-cri", "~> 0.1.0"
gem "fluent-plugin-logzio", "~> 0.0.18"
gem "fluent-plugin-cloudwatch-logs", "~> 0.14.3"
gem 'fluent-plugin-kubernetes', "0.3.1"
gem "fluent-plugin-kubernetes_metadata_filter", "~> 3.2.0"
gem 'fluent-plugin-papertrail', "0.2.8"
gem 'fluent-plugin-prometheus', "2.1.0"
gem 'fluent-plugin-record-modifier', "2.1.0"
gem 'fluent-plugin-record-reformer', "0.9.1"
gem "fluent-plugin-systemd", "~> 1.0.5"
gem 'fluent-plugin-uri-parser', "0.3.0"
gem 'fluent-plugin-vmware-loginsight', "1.4.1"
gem 'fluent-plugin-vmware-log-intelligence', "2.0.8"
# fluent-plugin-mysqlslowquery is dependency for fluent-plugin-vmware-log-intelligence
gem 'fluent-plugin-mysqlslowquery', "0.0.9"
gem 'fluent-plugin-throttle', '0.0.5'
gem 'fluent-plugin-detect-exceptions', '0.0.14'
gem 'gelf', "3.1.0"
gem 'logfmt', "0.0.10"
gem 'kubeclient', "~> 4.9.3"
gem 'fluent-plugin-webhdfs', '1.5.0'
# webhdfs requires gssapi plugin to work
gem 'gssapi', '1.3.1'
gem 'specific_install', '0.3.8'
